config/routes.rb
Rails.application.routes.draw do

  resources :activities

  root 'users#index'

  get 'users/new' => 'users#new'
  post 'users' => 'users#create'
  get '/users/:id' => 'users#show', as: :user
  get '/profile' => 'users#show'
  get '/users/:id/edit' => 'users#edit'
  patch '/users/:id' => 'users#update'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get "activities/:id/edit" => "activities#edit"
  delete "activities/:id/destroy" => "activities#destroy"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :activities

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activity = Activity.all.order(created_at: 'DESC')
    @user = User.find(session[:user_id])
    # @activity = @user.activity.all
  end

  def new
    @activity = Activity.new
    @user = User.find(session[:user_id])

  end

  def create

    @activity = Activity.new(activity_params)
    @activity.user_id = session[:user_id]
    if @activity.save
      redirect_to '/profile'
    else
      render :new
    end
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def update
    @activity = Activity.find(params[:id])
    if @activity.update_attributes(activity_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  def show
    @activity = Activity.find(params[:id])
  end

  def destroy

    activity = Activity.find(params[:id])
    activity.destroy
    redirect_to '/profile', :notice => "You destroyed a like"
    # Activity.find(params[:id]).destroy
    # redirect_to '/profile'
  end

private
  def activity_params
    params.require(:activity).permit(:title, :when, :description)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :null_session
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
      user = User.find_by(email: params[:login][:email])
      if user && user.authenticate(params[:login][:password])
        session[:user_id] = user.id
        redirect_to user_path(user)
      else
        render :new
      end
  end

  def destroy
      session.delete(:user_id)
      redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    redirect_to '/' unless session[:user_id]
    @user = User.find(session[:user_id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :status, :password, :password_confirmation, :avatar)
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
      @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/edit.html.erb
<div class="col-md-4">
<h3>Edit your activites</h3>

<%= form_for @activity do |f| %>
  <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
  </div>
  <div class="row-fluid">
    <div class="span6">
      <%= f.label :description %> <br>
      <%= text_area(:description, :activity, cols: 100, rows: 10) %>
    </div>
  </div>
  <div>
      <%= f.label :when %>
      <%= f.select :when, options_for_select([["Select One", ""], "past", "present", "future"]) %>
  <div>
      <%= f.submit 'save' %>
  </div>
<% end %>

app/views/activities/new.html.erb
<%= form_for @activity do |f| %>
  <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
  </div>
    <div>
      <%= f.label :description %> <br>
      <%= text_area(:description, :activity, cols: 100, rows: 10) %>
    </div>
  <div>
      <%= f.label :when %>
      <%= f.select :when, options_for_select([["Select One", ""], "past", "present", "future"]) %>
  <div>
      <%= f.submit %>
  </div>
<% end %>

app/views/activities/show.html.erb
<div class="col-md-4 col-md-offset-4">
<h3>Activities</h3>
  <ul>
      <li>
      <%= link_to @activity.title %> <br>
      <%= @activity.description %> <br>
      <%= @activity.when %> <br>
      <%= @activity.user_id %>
      </li>
  </ul>
      <div>
      <%= link_to 'Delete', @activity, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GA-Hub</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body class="container">
<%= image_tag("GA.jpg") %>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header col-md-4 col-md-offset-4">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" href="#">Brand</a> -->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav col-md-4 col-md-offset-4">
        <% if current_user %>
          <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
          <li><%= link_to 'Add Activity', new_activity_path %></li>
        <% else %>
          <li><%= link_to 'Log in', login_path %></li>
          <li><%= link_to 'Sign up', users_new_path %></li>
        <% end %>
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>-->
      </ul>
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>-->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<h1>edit</h1>


<%= form_for @user do |f| %>
  <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
  </div>
  <div>
      <%= f.label :email %>
      <%= f.text_field :email %>
  </div>
  <div>
      <%= f.label :status %>
      <%= f.select :status, options_for_select([["Select One", ""], "prospective student", "student", "graduate"]) %>
  </div>
  <div>
      <%= f.label :avatar %>
      <%= f.file_field :avatar %>
  </div>
  <div>
      <%= f.label :password %>
      <%= f.password_field :password %>
  </div>
   <div>
      <%= f.label :password_confimation %>
      <%= f.password_field :password_confirmation %>
  </div>
  <div>
      <%= f.submit 'edit' %>
  </div>
<% end %>

app/views/users/index.html.erb
<% if current_user %>
<h1>Users</h1>
  <ul>
    <% @users.each do |user| %>
    <li><%= user.email %> - <%= user.password_digest %> - <%= user.name %> </li>
<% end %>
  </ul>

  <form action="/logout" method="post">
    <input name="_method" value="DELETE" type="hidden">
    <button>Logout</button>
  </form>
<% else %>
    <h2 class=intro>Bringing future, present and past General Assembly students together <br></h2>
    <h6 class="intro submit"> Please log in </h6>
<% end %>

app/views/users/new.html.erb
<div class="col-md-4 col-md-offset-4">
<h1 class="intro">Sign Up</h1>


<%= form_for @user do |f| %>
  <div>
      <%= f.label :name %> <br>
      <%= f.text_field :name %>
  </div>
  <div>
      <%= f.label :email %> <br>
      <%= f.text_field :email %>
  </div>
  <div>
      <%= f.label :password %> <br>
      <%= f.password_field :password %>
  </div>
   <div>
      <%= f.label :password_confimation %> <br>
      <%= f.password_field :password_confirmation %>
  </div>
  <div>
      <%= f.label :status %> <br>
      <%= f.select :status, options_for_select([["Select One", ""], "prospective student", "student", "graduate"]) %>
  </div>
  <div>
      <%= f.label :avatar %> <br>
      <%= f.file_field :avatar %>
  </div>

  <div class="submit">
      <%= f.submit 'Submit' %>
  </div>
<% end %>
</div>

app/views/users/show.html.erb
<div class="user col-md-4 col-md-offset-4">
    <%= image_tag @user.avatar.url(:medium) %>
    <%= @user.name %> <br>
    <%= @user.email %> <br>
    <%= @user.status %> <br>
</div>

<h4 class="intro submit col-md-4 col-md-offset-4">Activities</h4>



    <% @user.activities.each do |activity| %>
    <div class="row">
        <table class=" activity table table-inverse">
        <thead>
            <th><%= link_to activity.title, activity_path(activity.id) %></th>
        </thead>
        <tbody >
            <td class="block"><%= link_to 'Delete', activity_path(activity.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <td class="block"><%= link_to 'Edit', edit_activity_path(activity.id) %></td>
        </tbody>
        </table>
    </div>
    <% end %>